version: "3"

services:
  backend:
    container_name: nhb-backend
    image: nhb-backend
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    ports:
      - "8080:8080"
    restart: always

  db:
    container_name: nhb-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
